version: '3.7'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: chrisgram-server
    container_name: chrisgram-node-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: unless-stopped
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: chrisgram-client
    container_name: chrisgram-react-client
    depends_on:
      - server
    restart: unless-stopped
    ports:
      - "3000:3000"
volumes:
  data-volume: